import Foundation

/// QPay API error code string constants.
public enum QPayErrorCode {
    public static let accountBankDuplicated = "ACCOUNT_BANK_DUPLICATED"
    public static let accountSelectionInvalid = "ACCOUNT_SELECTION_INVALID"
    public static let authenticationFailed = "AUTHENTICATION_FAILED"
    public static let bankAccountNotFound = "BANK_ACCOUNT_NOTFOUND"
    public static let bankMCCAlreadyAdded = "BANK_MCC_ALREADY_ADDED"
    public static let bankMCCNotFound = "BANK_MCC_NOT_FOUND"
    public static let cardTerminalNotFound = "CARD_TERMINAL_NOTFOUND"
    public static let clientNotFound = "CLIENT_NOTFOUND"
    public static let clientUsernameDuplicated = "CLIENT_USERNAME_DUPLICATED"
    public static let customerDuplicate = "CUSTOMER_DUPLICATE"
    public static let customerNotFound = "CUSTOMER_NOTFOUND"
    public static let customerRegisterInvalid = "CUSTOMER_REGISTER_INVALID"
    public static let ebarimtCancelNotSupported = "EBARIMT_CANCEL_NOTSUPPERDED"
    public static let ebarimtNotRegistered = "EBARIMT_NOT_REGISTERED"
    public static let ebarimtQRCodeInvalid = "EBARIMT_QR_CODE_INVALID"
    public static let informNotFound = "INFORM_NOTFOUND"
    public static let inputCodeRegistered = "INPUT_CODE_REGISTERED"
    public static let inputNotFound = "INPUT_NOTFOUND"
    public static let invalidAmount = "INVALID_AMOUNT"
    public static let invalidObjectType = "INVALID_OBJECT_TYPE"
    public static let invoiceAlreadyCanceled = "INVOICE_ALREADY_CANCELED"
    public static let invoiceCodeInvalid = "INVOICE_CODE_INVALID"
    public static let invoiceCodeRegistered = "INVOICE_CODE_REGISTERED"
    public static let invoiceLineRequired = "INVOICE_LINE_REQUIRED"
    public static let invoiceNotFound = "INVOICE_NOTFOUND"
    public static let invoicePaid = "INVOICE_PAID"
    public static let invoiceReceiverDataAddressRequired = "INVOICE_RECEIVER_DATA_ADDRESS_REQUIRED"
    public static let invoiceReceiverDataEmailRequired = "INVOICE_RECEIVER_DATA_EMAIL_REQUIRED"
    public static let invoiceReceiverDataPhoneRequired = "INVOICE_RECEIVER_DATA_PHONE_REQUIRED"
    public static let invoiceReceiverDataRequired = "INVOICE_RECEIVER_DATA_REQUIRED"
    public static let maxAmountError = "MAX_AMOUNT_ERR"
    public static let mccNotFound = "MCC_NOTFOUND"
    public static let merchantAlreadyRegistered = "MERCHANT_ALREADY_REGISTERED"
    public static let merchantInactive = "MERCHANT_INACTIVE"
    public static let merchantNotFound = "MERCHANT_NOTFOUND"
    public static let minAmountError = "MIN_AMOUNT_ERR"
    public static let noCredentials = "NO_CREDENDIALS"
    public static let objectDataError = "OBJECT_DATA_ERROR"
    public static let p2pTerminalNotFound = "P2P_TERMINAL_NOTFOUND"
    public static let paymentAlreadyCanceled = "PAYMENT_ALREADY_CANCELED"
    public static let paymentNotPaid = "PAYMENT_NOT_PAID"
    public static let paymentNotFound = "PAYMENT_NOTFOUND"
    public static let permissionDenied = "PERMISSION_DENIED"
    public static let qrAccountInactive = "QRACCOUNT_INACTIVE"
    public static let qrAccountNotFound = "QRACCOUNT_NOTFOUND"
    public static let qrCodeNotFound = "QRCODE_NOTFOUND"
    public static let qrCodeUsed = "QRCODE_USED"
    public static let senderBranchDataRequired = "SENDER_BRANCH_DATA_REQUIRED"
    public static let taxLineRequired = "TAX_LINE_REQUIRED"
    public static let taxProductCodeRequired = "TAX_PRODUCT_CODE_REQUIRED"
    public static let transactionNotApproved = "TRANSACTION_NOT_APPROVED"
    public static let transactionRequired = "TRANSACTION_REQUIRED"
}
